# Secret for application
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-tls-secret
type: Opaque
data:
  "tls.crt": |-
    {{ .Files.Get "files/weit-ifm-1.0.5.chart-example.voicelab.local.crt" | b64enc }}
  "tls.key": |-
    {{ .Files.Get "files/weit-ifm-1.0.5.chart-example.voicelab.local.key" | b64enc }}
---
# Below two secrets are for nginx ingress controller(2 way SSL)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-client-secret
type: Opaque
data:
  "client.crt": |-
    {{ .Files.Get "files/client.crt" | b64enc }}
  "client.key": |-
    {{ .Files.Get "files/client.key" | b64enc }}
  "ca.crt": |-
    {{ .Files.Get "files/ca.crt" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-server-secret
type: Opaque
data:
  "server.crt": |-
    {{ .Files.Get "files/server.crt" | b64enc }}
  "server.key": |-
    {{ .Files.Get "files/server.key" | b64enc }}
  "ca.crt": |-
    {{ .Files.Get "files/ca.crt" | b64enc }}
